/**
 * Every photograph on the site, from Unsplash (https://unsplash.com/license).
 * Images are hot-linked from Unsplash's CDN as their API guidelines require,
 * and photographers are credited on /credits. `npm run photos` pings the
 * download endpoint for each entry, which the guidelines also ask for.
 *
 * PLACEHOLDER — product photographs are stand-ins. Replace them with the
 * distributor's official shots of each model before launch.
 */

export interface Photo {
  id: string
  /** Unsplash CDN base URL — sized by the image loader. */
  src: string
  width: number
  height: number
  /** Dominant colour, shown while the image loads. */
  color: string
  alt: string
  author: string
  authorUrl: string
  page: string
  /** Unsplash download-tracking endpoint (pinged by `npm run photos`). */
  download: string
}

export const photos = {
  persol3092: {
    id: 'agis2A366g8',
    src: 'https://images.unsplash.com/photo-1588937094793-5aee482cd9a0',
    width: 4480,
    height: 6720,
    color: '#f3f3f3',
    alt: "Monture optique Persol en écaille, gros plan sur la branche gravée",
    author: "Howard Bouchevereau",
    authorUrl: 'https://unsplash.com/@howardbouchevereau',
    page: 'https://unsplash.com/photos/silver-framed-eyeglasses-on-gray-textile-agis2A366g8',
    download: 'https://api.unsplash.com/photos/agis2A366g8/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MXx8cGVyc29sJTIwc3VuZ2xhc3Nlc3xlbnwxfHx8fDE3OTA5NDU0MDl8MA',
  },
  omalley: {
    id: 's7gRHGEmX78',
    src: 'https://images.unsplash.com/photo-1603578119639-798b8413d8d7',
    width: 4923,
    height: 3282,
    color: '#f3f3f3',
    alt: "Monture ronde en acétate écaille posée sur fond clair",
    author: "Oli Woodman",
    authorUrl: 'https://unsplash.com/@braintax',
    page: 'https://unsplash.com/photos/black-and-brown-framed-eyeglasses-s7gRHGEmX78',
    download: 'https://api.unsplash.com/photos/s7gRHGEmX78/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MXx8ZXllZ2xhc3NlcyUyMHByb2R1Y3QlMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3OTA5NDU0MTh8MA',
  },
  lemtosh: {
    id: 'MNb1ROebylg',
    src: 'https://images.unsplash.com/photo-1641048927024-0e801784b4f7',
    width: 6000,
    height: 3376,
    color: '#d9d9d9',
    alt: "Petite monture ronde noire en acétate épais",
    author: "Cosmin Ursea",
    authorUrl: 'https://unsplash.com/@cosminursea',
    page: 'https://unsplash.com/photos/a-pair-of-glasses-sitting-on-top-of-a-table-MNb1ROebylg',
    download: 'https://api.unsplash.com/photos/MNb1ROebylg/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8N3x8cm91bmQlMjBleWVnbGFzc2VzfGVufDF8fHx8MTc5MDk0NTQxNHww',
  },
  clubmasterRx: {
    id: 'd05w6_7FaPM',
    src: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371',
    width: 5184,
    height: 3456,
    color: '#d9d9d9',
    alt: "Monture à sourcils écaille et métal argenté posée sur un livre blanc",
    author: "Sincerely Media",
    authorUrl: 'https://unsplash.com/@sincerelymedia',
    page: 'https://unsplash.com/photos/clear-eyeglasses-on-book-d05w6_7FaPM',
    download: 'https://api.unsplash.com/photos/d05w6_7FaPM/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8Mnx8Z2xhc3NlcyUyMG9uJTIwYm9va3xlbnwxfHx8fDE3OTA5NDU0NDB8MA',
  },
  lindberg: {
    id: 'LXe6TKKxj44',
    src: 'https://images.unsplash.com/photo-1574065557312-b7cc977d8a89',
    width: 4000,
    height: 6000,
    color: '#c0c0c0',
    alt: "Monture en métal argenté à double pont, en noir et blanc",
    author: "Aarif Sheikh",
    authorUrl: 'https://unsplash.com/@aarif_15',
    page: 'https://unsplash.com/photos/grey-framed-eyeglasses-LXe6TKKxj44',
    download: 'https://api.unsplash.com/photos/LXe6TKKxj44/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8OHx8ZXllZ2xhc3NlcyUyMHByb2R1Y3QlMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3OTA5NDU0MTh8MA',
  },
  mykita: {
    id: '891Mi4ZbXZs',
    src: 'https://images.unsplash.com/photo-1786341133584-bdb6ec4da674',
    width: 6000,
    height: 4000,
    color: '#262626',
    alt: "Monture ronde fine en métal sur fond noir",
    author: "Spencer Liao",
    authorUrl: 'https://unsplash.com/@spencerliao',
    page: 'https://unsplash.com/photos/round-silver-eyeglass-lens-891Mi4ZbXZs',
    download: 'https://api.unsplash.com/photos/891Mi4ZbXZs/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MjF8fGNsZWFyJTIwZnJhbWUlMjBnbGFzc2VzfGVufDF8fHx8MTc5MDk0NTQyMnww',
  },
  wilson: {
    id: 'LaXCHG-yCJg',
    src: 'https://images.unsplash.com/photo-1701252374715-b5d8ab0b5f2c',
    width: 2832,
    height: 3540,
    color: '#f3f3f3',
    alt: "Monture pantos en acétate cristal sur fond blanc",
    author: "Irene Kredenets",
    authorUrl: 'https://unsplash.com/@ikredenets',
    page: 'https://unsplash.com/photos/a-pair-of-glasses-sitting-on-top-of-a-table-LaXCHG-yCJg',
    download: 'https://api.unsplash.com/photos/LaXCHG-yCJg/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MXx8Y2xlYXIlMjBmcmFtZSUyMGdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDIyfDA',
  },
  tfOptical: {
    id: 'GjH27_ZEjq8',
    src: 'https://images.unsplash.com/photo-1760446032123-f66e0c7a005b',
    width: 4000,
    height: 2666,
    color: '#260c0c',
    alt: "Monture papillon noire posée sur une table en noyer",
    author: "ZEELOOL Glasses",
    authorUrl: 'https://unsplash.com/@zeelool_official',
    page: 'https://unsplash.com/photos/black-eyeglasses-resting-on-a-wooden-surface-GjH27_ZEjq8',
    download: 'https://api.unsplash.com/photos/GjH27_ZEjq8/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTR8fGNsZWFyJTIwZnJhbWUlMjBnbGFzc2VzfGVufDF8fHx8MTc5MDk0NTQyMnww',
  },
  santos: {
    id: 'yQmtYxCgL4c',
    src: 'https://images.unsplash.com/photo-1585108570558-dced27973d0d',
    width: 6000,
    height: 4000,
    color: '#262626',
    alt: "Solaires en métal doré aux verres fumés sur fond noir",
    author: "Eduardo Diogo",
    authorUrl: 'https://unsplash.com/@erdiogo',
    page: 'https://unsplash.com/photos/gold-framed-eyeglasses-on-black-surface-yQmtYxCgL4c',
    download: 'https://api.unsplash.com/photos/yQmtYxCgL4c/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTh8fGdvbGQlMjBtZXRhbCUyMGdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDM4fDA',
  },
  wayfarer: {
    id: 'K62u25Jk6vo',
    src: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f',
    width: 6000,
    height: 6000,
    color: '#f3f3f3',
    alt: "Ray-Ban Wayfarer noires sur fond blanc",
    author: "Giorgio Trovato",
    authorUrl: 'https://unsplash.com/@giorgiotrovato',
    page: 'https://unsplash.com/photos/shallow-focus-photo-of-black-ray-ban-wayfarer-sunglasses-K62u25Jk6vo',
    download: 'https://api.unsplash.com/photos/K62u25Jk6vo/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MXx8cmF5LWJhbiUyMHN1bmdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDA3fDA',
  },
  aviator: {
    id: 'uA1bZsgrTTs',
    src: 'https://images.unsplash.com/photo-1567101293231-51d2bd439398',
    width: 5184,
    height: 3456,
    color: '#d9d9d9',
    alt: "Ray-Ban Aviator dorées aux verres verts posées sur une pierre",
    author: "loganathan logesh",
    authorUrl: 'https://unsplash.com/@logesh_5567',
    page: 'https://unsplash.com/photos/gold-ray-ban-aviator-sunglasses-uA1bZsgrTTs',
    download: 'https://api.unsplash.com/photos/uA1bZsgrTTs/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8NHx8YXZpYXRvciUyMHN1bmdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDExfDA',
  },
  gucciHex: {
    id: 'oAdlWXpuYiQ',
    src: 'https://images.unsplash.com/photo-1774791697894-42dacd95807d',
    width: 5184,
    height: 3456,
    color: '#408ca6',
    alt: "Solaires Gucci hexagonales dorées sur leur pochette",
    author: "L Photography",
    authorUrl: 'https://unsplash.com/@lphotohraphy',
    page: 'https://unsplash.com/photos/gold-rimmed-aviator-sunglasses-on-a-teal-gucci-pouch-oAdlWXpuYiQ',
    download: 'https://api.unsplash.com/photos/oAdlWXpuYiQ/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTh8fGF2aWF0b3IlMjBzdW5nbGFzc2VzfGVufDF8fHx8MTc5MDk0NTQxMXww',
  },
  persol714: {
    id: 'cMz5kGMmdnw',
    src: 'https://images.unsplash.com/photo-1788500657788-ddd329542124',
    width: 3789,
    height: 5684,
    color: '#262626',
    alt: "Solaires en écaille posées sur un cuir sombre",
    author: "Luiz Rogério Nunes",
    authorUrl: 'https://unsplash.com/@luizr_ph',
    page: 'https://unsplash.com/photos/tortoiseshell-sunglasses-on-leather-surface-cMz5kGMmdnw',
    download: 'https://api.unsplash.com/photos/cMz5kGMmdnw/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8Mnx8c3VuZ2xhc3NlcyUyMHByb2R1Y3QlMjBkYXJrJTIwYmFja2dyb3VuZHxlbnwxfHx8fDE3OTA5NDU0MjB8MA',
  },
  triomphe: {
    id: 'VSAk8yv28eg',
    src: 'https://images.unsplash.com/photo-1760446031507-ed534e0f9605',
    width: 4000,
    height: 2666,
    color: '#8c8c73',
    alt: "Solaires papillon en écaille sur fond crème",
    author: "ZEELOOL Glasses",
    authorUrl: 'https://unsplash.com/@zeelool_official',
    page: 'https://unsplash.com/photos/tortoiseshell-sunglasses-with-gold-accents-on-a-light-surface-VSAk8yv28eg',
    download: 'https://api.unsplash.com/photos/VSAk8yv28eg/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8NHx8Y2F0JTIwZXllJTIwc3VuZ2xhc3Nlc3xlbnwxfHx8fDE3OTA5NDU0MTZ8MA',
  },
  sl276: {
    id: 'SZ4kMcf6G4s',
    src: 'https://images.unsplash.com/photo-1760446032732-c042b0d43580',
    width: 6000,
    height: 4000,
    color: '#0c2640',
    alt: "Solaires papillon noires sur un escalier sombre",
    author: "ZEELOOL Glasses",
    authorUrl: 'https://unsplash.com/@zeelool_official',
    page: 'https://unsplash.com/photos/black-cat-eye-sunglasses-on-a-textured-surface-SZ4kMcf6G4s',
    download: 'https://api.unsplash.com/photos/SZ4kMcf6G4s/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8M3x8Y2F0JTIwZXllJTIwc3VuZ2xhc3Nlc3xlbnwxfHx8fDE3OTA5NDU0MTZ8MA',
  },
  symbole: {
    id: 'Vvpt0i-6xjU',
    src: 'https://images.unsplash.com/photo-1764740120242-77f9f5e3b63f',
    width: 3899,
    height: 4874,
    color: '#f3f3f3',
    alt: "Solaires noires à branches épaisses sur fond blanc",
    author: "Vooglam Eyewear",
    authorUrl: 'https://unsplash.com/@vooglam_official',
    page: 'https://unsplash.com/photos/black-cat-eye-sunglasses-on-a-white-background-Vvpt0i-6xjU',
    download: 'https://api.unsplash.com/photos/Vvpt0i-6xjU/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8M3x8c3VuZ2xhc3NlcyUyMHByb2R1Y3QlMjBkYXJrJTIwYmFja2dyb3VuZHxlbnwxfHx8fDE3OTA5NDU0MjB8MA',
  },
  snowdon: {
    id: 'jS-vBufwKyY',
    src: 'https://images.unsplash.com/photo-1760446032400-506ec8963e6a',
    width: 4989,
    height: 4000,
    color: '#d9d9d9',
    alt: "Solaires noires posées sur un socle de pierre",
    author: "ZEELOOL Glasses",
    authorUrl: 'https://unsplash.com/@zeelool_official',
    page: 'https://unsplash.com/photos/tortoiseshell-sunglasses-resting-on-a-stone-pedestal-jS-vBufwKyY',
    download: 'https://api.unsplash.com/photos/jS-vBufwKyY/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8M3x8dG9ydG9pc2VzaGVsbCUyMGdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDEyfDA',
  },
  rbBlue: {
    id: 'fWGMEbTzVAE',
    src: 'https://images.unsplash.com/photo-1625591339971-4c9a87a66871',
    width: 3444,
    height: 2688,
    color: '#a6c0d9',
    alt: "Monture transparente posée sur fond bleu",
    author: "Redowan Dhrubo",
    authorUrl: 'https://unsplash.com/@redowandhrubo',
    page: 'https://unsplash.com/photos/silver-framed-eyeglasses-on-white-surface-fWGMEbTzVAE',
    download: 'https://api.unsplash.com/photos/fWGMEbTzVAE/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8Mnx8Y2xlYXIlMjBmcmFtZSUyMGdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDIyfDA',
  },
  mp2: {
    id: 'PnsfHpDrY5o',
    src: 'https://images.unsplash.com/photo-1602703522866-fb486308da5d',
    width: 5184,
    height: 3456,
    color: '#f3f3f3',
    alt: "Monture ronde en métal noir et doré sur fond blanc",
    author: "Franco Antonio Giovanella",
    authorUrl: 'https://unsplash.com/@francogio',
    page: 'https://unsplash.com/photos/brown-framed-eyeglasses-on-white-surface-PnsfHpDrY5o',
    download: 'https://api.unsplash.com/photos/PnsfHpDrY5o/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8NHx8ZXllZ2xhc3NlcyUyMHByb2R1Y3QlMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3OTA5NDU0MTh8MA',
  },
  junior: {
    id: 'e8TtkC5xyv4',
    src: 'https://images.unsplash.com/photo-1556306510-31ca015374b0',
    width: 6000,
    height: 4000,
    color: '#d9d9d9',
    alt: "Monture enfant rectangulaire noire sur fond clair",
    author: "Claudio Schwarz",
    authorUrl: 'https://unsplash.com/@purzlbaum',
    page: 'https://unsplash.com/photos/black-framed-eyeglasses-e8TtkC5xyv4',
    download: 'https://api.unsplash.com/photos/e8TtkC5xyv4/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MXx8a2lkcyUyMGdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDIzfDA',
  },
  juniorRound: {
    id: 'MNb1ROebylg',
    src: 'https://images.unsplash.com/photo-1641048927024-0e801784b4f7',
    width: 6000,
    height: 3376,
    color: '#d9d9d9',
    alt: "Petite monture ronde noire pour enfant",
    author: "Cosmin Ursea",
    authorUrl: 'https://unsplash.com/@cosminursea',
    page: 'https://unsplash.com/photos/a-pair-of-glasses-sitting-on-top-of-a-table-MNb1ROebylg',
    download: 'https://api.unsplash.com/photos/MNb1ROebylg/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8NXx8a2lkcyUyMGdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDIzfDA',
  },
  nanovista: {
    id: 'ogav-IaToZI',
    src: 'https://images.unsplash.com/photo-1716862182572-10603d9089a6',
    width: 7218,
    height: 4817,
    color: '#f3f3f3',
    alt: "Montures enfant colorées disposées à plat",
    author: "GlassesShop",
    authorUrl: 'https://unsplash.com/@glassesshop_9',
    page: 'https://unsplash.com/photos/six-pairs-of-glasses-sitting-on-top-of-a-white-surface-ogav-IaToZI',
    download: 'https://api.unsplash.com/photos/ogav-IaToZI/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8OXx8a2lkcyUyMGdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDIzfDA',
  },
  caseHard: {
    id: 'x6BFZQ_2YEw',
    src: 'https://images.unsplash.com/photo-1632986636968-04958bfbbf3f',
    width: 4494,
    height: 5617,
    color: '#262626',
    alt: "Étui rigide blanc ouvert sur une paire de lunettes",
    author: "Robert Torres",
    authorUrl: 'https://unsplash.com/@roberttorres_19r',
    page: 'https://unsplash.com/photos/a-pair-of-glasses-in-a-case-on-a-table-x6BFZQ_2YEw',
    download: 'https://api.unsplash.com/photos/x6BFZQ_2YEw/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MXx8Z2xhc3NlcyUyMGNhc2V8ZW58MXx8fHwxNzkwOTQ1NDI1fDA',
  },
  caseLeather: {
    id: 'qKyj3Yu18co',
    src: 'https://images.unsplash.com/photo-1586806828699-f06085feb6c5',
    width: 3648,
    height: 5472,
    color: '#260c0c',
    alt: "Étui en cuir fauve et monture cristal dans la pénombre",
    author: "Priscilla Du Preez 🇨🇦",
    authorUrl: 'https://unsplash.com/@priscilladupreez',
    page: 'https://unsplash.com/photos/silver-framed-eyeglasses-beside-brown-leather-wallet-qKyj3Yu18co',
    download: 'https://api.unsplash.com/photos/qKyj3Yu18co/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MjJ8fGNsZWFyJTIwZnJhbWUlMjBnbGFzc2VzfGVufDF8fHx8MTc5MDk0NTQyMnww',
  },
  pochette: {
    id: 'w2HBGgyS9gU',
    src: 'https://images.unsplash.com/photo-1665525549743-9c9ab3ad1972',
    width: 6000,
    height: 4000,
    color: '#262626',
    alt: "Pochette en velours avec cordon, à côté de montures noires",
    author: "Amr Taha™",
    authorUrl: 'https://unsplash.com/@amr_taha',
    page: 'https://unsplash.com/photos/a-brown-leather-shoe-w2HBGgyS9gU',
    download: 'https://api.unsplash.com/photos/w2HBGgyS9gU/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8Mnx8bGVucyUyMGNsZWFuaW5nJTIwY2xvdGglMjBnbGFzc2VzfGVufDF8fHx8MTc5MDk0NTY2N3ww',
  },
  cloth: {
    id: 'XKXHXdQhjos',
    src: 'https://images.unsplash.com/photo-1658372856268-670fa8aa4e3b',
    width: 4217,
    height: 5600,
    color: '#262626',
    alt: "Monture posée sur une chamoisine noire",
    author: "Obi",
    authorUrl: 'https://unsplash.com/@obionyeador',
    page: 'https://unsplash.com/photos/a-pair-of-headphones-on-a-desk-XKXHXdQhjos',
    download: 'https://api.unsplash.com/photos/XKXHXdQhjos/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8M3x8bGVucyUyMGNsZWFuaW5nJTIwY2xvdGglMjBnbGFzc2VzfGVufDF8fHx8MTc5MDk0NTY2N3ww',
  },
  kit: {
    id: 'OEEueTw74dk',
    src: 'https://images.unsplash.com/photo-1593182419348-352e5b437d07',
    width: 2695,
    height: 1964,
    color: '#262626',
    alt: "Chiffon, étui et lunettes sur un bureau sombre",
    author: "Aryan Singh",
    authorUrl: 'https://unsplash.com/@aryansingh0634',
    page: 'https://unsplash.com/photos/black-click-pen-on-black-leather-case-OEEueTw74dk',
    download: 'https://api.unsplash.com/photos/OEEueTw74dk/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTV8fGxlbnMlMjBjbGVhbmluZyUyMGNsb3RoJTIwZ2xhc3Nlc3xlbnwxfHx8fDE3OTA5NDU2Njd8MA',
  },
  chain: {
    id: 'yKB_hLMCeRI',
    src: 'https://images.unsplash.com/photo-1761896877961-90b19228334f',
    width: 3837,
    height: 4796,
    color: '#f38c26',
    alt: "Deux montures reliées par des chaînes argentées",
    author: "Vooglam Eyewear",
    authorUrl: 'https://unsplash.com/@vooglam_official',
    page: 'https://unsplash.com/photos/two-pairs-of-glasses-with-chains-on-orange-background-yKB_hLMCeRI',
    download: 'https://api.unsplash.com/photos/yKB_hLMCeRI/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MXx8ZXllZ2xhc3NlcyUyMGNoYWlufGVufDF8fHx8MTc5MDk0NTY2NXww',
  },
  giftBox: {
    id: 'Qyp0OvNhPyc',
    src: 'https://images.unsplash.com/photo-1607614564906-234871d9608f',
    width: 5760,
    height: 3840,
    color: '#c0c0c0',
    alt: "Coffrets blancs fermés par un ruban noir",
    author: "filiz conn",
    authorUrl: 'https://unsplash.com/@fconn',
    page: 'https://unsplash.com/photos/black-and-white-gift-box-with-ribbon-Qyp0OvNhPyc',
    download: 'https://api.unsplash.com/photos/Qyp0OvNhPyc/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTh8fGJsYWNrJTIwZ2lmdCUyMGJveCUyMHJpYmJvbnxlbnwxfHx8fDE3OTA5NDU2Njl8MA',
  },
  worldOptical: {
    id: '0WYgQLYL3Co',
    src: 'https://images.unsplash.com/photo-1588768904397-cb062c91ba55',
    width: 5863,
    height: 3909,
    color: '#f3f3f3',
    alt: "Monture ronde noire à côté d’un appareil Leica, en noir et blanc",
    author: "vitoandwilly",
    authorUrl: 'https://unsplash.com/@vitowilly',
    page: 'https://unsplash.com/photos/black-and-silver-camera-on-white-table-0WYgQLYL3Co',
    download: 'https://api.unsplash.com/photos/0WYgQLYL3Co/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MjR8fGV5ZWdsYXNzZXMlMjBwcm9kdWN0JTIwcGhvdG9ncmFwaHl8ZW58MXx8fHwxNzkwOTQ1NDE4fDA',
  },
  worldSun: {
    id: 'dtOTQYmTEs0',
    src: 'https://images.unsplash.com/photo-1577803645773-f96470509666',
    width: 7020,
    height: 4680,
    color: '#f3d9d9',
    alt: "Solaires cristal posées sur le sable face à la mer",
    author: "Sebastian Coman Travel",
    authorUrl: 'https://unsplash.com/@sebcomantravel',
    page: 'https://unsplash.com/photos/white-framed-brown-lens-sunglasses-dtOTQYmTEs0',
    download: 'https://api.unsplash.com/photos/dtOTQYmTEs0/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MXx8c3VuZ2xhc3NlcyUyMGJlYWNoJTIwbWVkaXRlcnJhbmVhbnxlbnwxfHx8fDE3OTA5NDU0NDJ8MA',
  },
  solder: {
    id: 'zgXnBplu2pg',
    src: 'https://images.unsplash.com/photo-1590077557404-1087807b2ea9',
    width: 2832,
    height: 3525,
    color: '#262626',
    alt: "Un artisan brase une monture métallique à la flamme",
    author: "sour moha",
    authorUrl: 'https://unsplash.com/@sour_moha',
    page: 'https://unsplash.com/photos/person-holding-red-and-green-paint-brush-zgXnBplu2pg',
    download: 'https://api.unsplash.com/photos/zgXnBplu2pg/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8OXx8ZXlld2VhciUyMHdvcmtzaG9wJTIwY3JhZnRzbWFufGVufDF8fHx8MTc5MDk0NTQzMXww',
  },
  hinge: {
    id: 'QiQeJ6JRrTY',
    src: 'https://images.unsplash.com/photo-1786341132619-25a28781d17e',
    width: 6000,
    height: 4000,
    color: '#f3f3f3',
    alt: "Macro d’une charnière en métal argenté",
    author: "Spencer Liao",
    authorUrl: 'https://unsplash.com/@spencerliao',
    page: 'https://unsplash.com/photos/silver-metal-eyeglass-frame-detail-QiQeJ6JRrTY',
    download: 'https://api.unsplash.com/photos/QiQeJ6JRrTY/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTh8fGNsZWFyJTIwZnJhbWUlMjBnbGFzc2VzfGVufDF8fHx8MTc5MDk0NTQyMnww',
  },
  exam: {
    id: 'okfR2olVQys',
    src: 'https://images.unsplash.com/photo-1616163477138-508df4131a38',
    width: 3556,
    height: 2595,
    color: '#262626',
    alt: "Réfracteur d’examen de la vue, en noir et blanc",
    author: "Quincy Follweiler",
    authorUrl: 'https://unsplash.com/@fortress',
    page: 'https://unsplash.com/photos/black-and-silver-dslr-camera-okfR2olVQys',
    download: 'https://api.unsplash.com/photos/okfR2olVQys/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8Mnx8b3B0b21ldHJpc3QlMjBleWUlMjBleGFtfGVufDF8fHx8MTc5MDk0NTQyOXww',
  },
  acetate: {
    id: 'Qh6eO-HaTIM',
    src: 'https://images.unsplash.com/photo-1787282810676-639860a6064d',
    width: 3840,
    height: 2560,
    color: '#260c0c',
    alt: "Monture en écaille posée sur une pierre, lumière rasante",
    author: "Juan Pablo",
    authorUrl: 'https://unsplash.com/@who0ne',
    page: 'https://unsplash.com/photos/eyeglasses-on-weathered-stone-ledge-Qh6eO-HaTIM',
    download: 'https://api.unsplash.com/photos/Qh6eO-HaTIM/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MjF8fHRvcnRvaXNlc2hlbGwlMjBnbGFzc2VzfGVufDF8fHx8MTc5MDk0NTQxMnww',
  },
  shopWall: {
    id: 'XbPhaw-x0i0',
    src: 'https://images.unsplash.com/photo-1615468822882-4828d2602857',
    width: 5472,
    height: 3648,
    color: '#c0c0c0',
    alt: "Présentoir de montures alignées en boutique",
    author: "Harpreet Singh",
    authorUrl: 'https://unsplash.com/@harpreetkaka',
    page: 'https://unsplash.com/photos/silver-framed-eyeglasses-on-clear-glass-XbPhaw-x0i0',
    download: 'https://api.unsplash.com/photos/XbPhaw-x0i0/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MXx8b3B0aWNpYW4lMjBzdG9yZXxlbnwxfHx8fDE3OTA5NDU0Mjd8MA',
  },
  shelves: {
    id: 'qZqVItlSuXc',
    src: 'https://images.unsplash.com/photo-1667964394328-78f6389e79ab',
    width: 4464,
    height: 2976,
    color: '#c0a68c',
    alt: "Étagères blanches où reposent des solaires",
    author: "Na sen",
    authorUrl: 'https://unsplash.com/@nasen',
    page: 'https://unsplash.com/photos/a-white-rectangular-object-with-black-dots-qZqVItlSuXc',
    download: 'https://api.unsplash.com/photos/qZqVItlSuXc/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8NHx8b3B0aWNpYW4lMjBzdG9yZXxlbnwxfHx8fDE3OTA5NDU0Mjd8MA',
  },
  door: {
    id: 'NDq2T9sjDQw',
    src: 'https://images.unsplash.com/photo-1689430719647-22b16c82bb4f',
    width: 3437,
    height: 4583,
    color: '#d9d9d9',
    alt: "Porte bleue cloutée de Sidi Bou Saïd",
    author: "Rayyân",
    authorUrl: 'https://unsplash.com/@rayyanbrh',
    page: 'https://unsplash.com/photos/a-blue-door-with-two-pots-of-plants-in-front-of-it-NDq2T9sjDQw',
    download: 'https://api.unsplash.com/photos/NDq2T9sjDQw/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8NHx8c2lkaSUyMGJvdSUyMHNhaWR8ZW58MXx8fHwxNzkwOTQ1NDM3fDA',
  },
  port: {
    id: 'TQym0vpnycA',
    src: 'https://images.unsplash.com/photo-1739048203303-f2076f963dcb',
    width: 6889,
    height: 4592,
    color: '#a6a6a6',
    alt: "Le port de Sidi Bou Saïd au crépuscule",
    author: "Hongbin",
    authorUrl: 'https://unsplash.com/@hbsun2013',
    page: 'https://unsplash.com/photos/a-view-of-a-harbor-with-a-lot-of-boats-TQym0vpnycA',
    download: 'https://api.unsplash.com/photos/TQym0vpnycA/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MjR8fHNpZGklMjBib3UlMjBzYWlkfGVufDF8fHx8MTc5MDk0NTQzN3ww',
  },
  floating: {
    id: 'PHRe-53FyRg',
    src: 'https://images.unsplash.com/photo-1758552322632-ba288778c770',
    width: 4535,
    height: 6047,
    color: '#404040',
    alt: "Montures dorées suspendues sur fond sombre",
    author: "Vooglam Eyewear",
    authorUrl: 'https://unsplash.com/@vooglam_official',
    page: 'https://unsplash.com/photos/three-pairs-of-modern-eyeglasses-on-a-dark-background-PHRe-53FyRg',
    download: 'https://api.unsplash.com/photos/PHRe-53FyRg/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTd8fGdvbGQlMjBtZXRhbCUyMGdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDM4fDA',
  },
  look1: {
    id: 'Afx8CERBi6I',
    src: 'https://images.unsplash.com/photo-1684607776189-24a70a10a804',
    width: 3906,
    height: 6000,
    color: '#262626',
    alt: "Portrait en noir et blanc d’un homme portant une monture ronde",
    author: "Nicolas Houdayer",
    authorUrl: 'https://unsplash.com/@ascalaphe',
    page: 'https://unsplash.com/photos/a-black-and-white-photo-of-a-man-with-glasses-Afx8CERBi6I',
    download: 'https://api.unsplash.com/photos/Afx8CERBi6I/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8OXx8bWFuJTIwd2VhcmluZyUyMGdsYXNzZXMlMjBwb3J0cmFpdCUyMGJsYWNrJTIwYW5kJTIwd2hpdGV8ZW58MXx8fHwxNzkwOTQ1NDM1fDA',
  },
  look2: {
    id: '-5VhImssRUk',
    src: 'https://images.unsplash.com/photo-1758888676940-9a807f0b7a8a',
    width: 6000,
    height: 4000,
    color: '#737359',
    alt: "Femme voilée ajustant ses solaires papillon",
    author: "Babak Eshaghian",
    authorUrl: 'https://unsplash.com/@babak22ir',
    page: 'https://unsplash.com/photos/woman-adjusting-her-sunglasses-outdoors-with-trees-behind--5VhImssRUk',
    download: 'https://api.unsplash.com/photos/-5VhImssRUk/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTF8fHdvbWFuJTIwd2VhcmluZyUyMHN1bmdsYXNzZXMlMjBwb3J0cmFpdHxlbnwxfHx8fDE3OTA5NDU0MzN8MA',
  },
  look3: {
    id: 'PM_RSWzJyFg',
    src: 'https://images.unsplash.com/photo-1646303741999-d11b218b162e',
    width: 6000,
    height: 4000,
    color: '#404040',
    alt: "Portrait en noir et blanc d’un homme barbu à lunettes fines",
    author: "Saif Taee",
    authorUrl: 'https://unsplash.com/@saif_taee',
    page: 'https://unsplash.com/photos/a-black-and-white-photo-of-a-man-wearing-glasses-PM_RSWzJyFg',
    download: 'https://api.unsplash.com/photos/PM_RSWzJyFg/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTd8fG1hbiUyMHdlYXJpbmclMjBnbGFzc2VzJTIwcG9ydHJhaXQlMjBibGFjayUyMGFuZCUyMHdoaXRlfGVufDF8fHx8MTc5MDk0NTQzNXww',
  },
  look4: {
    id: 'C4nAzx1WTeE',
    src: 'https://images.unsplash.com/photo-1767801292762-130e769128bc',
    width: 5184,
    height: 3456,
    color: '#d9a68c',
    alt: "Femme au bandana portant des solaires papillon noires",
    author: "Anton Acosta",
    authorUrl: 'https://unsplash.com/@ottelo',
    page: 'https://unsplash.com/photos/woman-wearing-sunglasses-and-red-bandana-C4nAzx1WTeE',
    download: 'https://api.unsplash.com/photos/C4nAzx1WTeE/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTV8fGNhdCUyMGV5ZSUyMHN1bmdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDE2fDA',
  },
  shapeRound: {
    id: '0zA84TFRjI8',
    src: 'https://images.unsplash.com/photo-1646084081219-1090f72a531c',
    width: 4794,
    height: 4000,
    color: '#f3f3f3',
    alt: "Monture ronde noire et dorée",
    author: "Bartosz Sujkowski",
    authorUrl: 'https://unsplash.com/@art441',
    page: 'https://unsplash.com/photos/a-pair-of-glasses-sitting-on-top-of-a-white-surface-0zA84TFRjI8',
    download: 'https://api.unsplash.com/photos/0zA84TFRjI8/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8Mnx8cm91bmQlMjBleWVnbGFzc2VzfGVufDF8fHx8MTc5MDk0NTQxNHww',
  },
  shapeSquare: {
    id: '6_hrdabRIuc',
    src: 'https://images.unsplash.com/photo-1658849197955-a6f85b6ab8c3',
    width: 4771,
    height: 3181,
    color: '#f3f3f3',
    alt: "Monture carrée noire à cerclage métal",
    author: "Melvyn Swingler",
    authorUrl: 'https://unsplash.com/@melvyn_photo',
    page: 'https://unsplash.com/photos/a-pair-of-sunglasses-6_hrdabRIuc',
    download: 'https://api.unsplash.com/photos/6_hrdabRIuc/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MjF8fGdsYXNzZXMlMjBvbiUyMGJvb2t8ZW58MXx8fHwxNzkwOTQ1NDQwfDA',
  },
  shapeRect: {
    id: 'ilSnKT1IMxE',
    src: 'https://images.unsplash.com/photo-1444427169197-de497742b62d',
    width: 4023,
    height: 2681,
    color: '#a6c0c0',
    alt: "Monture rectangulaire noire posée sur un livre",
    author: "Mari Helin",
    authorUrl: 'https://unsplash.com/@mari',
    page: 'https://unsplash.com/photos/black-framed-eyeglasses-on-white-printing-paper-ilSnKT1IMxE',
    download: 'https://api.unsplash.com/photos/ilSnKT1IMxE/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTJ8fGdsYXNzZXMlMjBvbiUyMGJvb2t8ZW58MXx8fHwxNzkwOTQ1NDQwfDA',
  },
  shapeCat: {
    id: 'GjH27_ZEjq8',
    src: 'https://images.unsplash.com/photo-1760446032123-f66e0c7a005b',
    width: 4000,
    height: 2666,
    color: '#260c0c',
    alt: "Monture papillon noire",
    author: "ZEELOOL Glasses",
    authorUrl: 'https://unsplash.com/@zeelool_official',
    page: 'https://unsplash.com/photos/black-eyeglasses-resting-on-a-wooden-surface-GjH27_ZEjq8',
    download: 'https://api.unsplash.com/photos/GjH27_ZEjq8/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8MTR8fGNsZWFyJTIwZnJhbWUlMjBnbGFzc2VzfGVufDF8fHx8MTc5MDk0NTQyMnww',
  },
  shapeAviator: {
    id: 'wf5Kszyi8Ao',
    src: 'https://images.unsplash.com/photo-1562548726-43b650c82f8e',
    width: 6000,
    height: 4000,
    color: '#d9c0a6',
    alt: "Aviateur argenté posé au sol",
    author: "Griffin Wooldridge",
    authorUrl: 'https://unsplash.com/@dzngriffin',
    page: 'https://unsplash.com/photos/gray-framed-sunglasses-on-selective-focus-photography-wf5Kszyi8Ao',
    download: 'https://api.unsplash.com/photos/wf5Kszyi8Ao/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8Mnx8YXZpYXRvciUyMHN1bmdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDExfDA',
  },
  shapeOversized: {
    id: 'kQRtNeFxAcw',
    src: 'https://images.unsplash.com/photo-1760446031441-65f456460d59',
    width: 2500,
    height: 3748,
    color: '#c08c73',
    alt: "Grande monture en écaille",
    author: "ZEELOOL Glasses",
    authorUrl: 'https://unsplash.com/@zeelool_official',
    page: 'https://unsplash.com/photos/tortoiseshell-eyeglasses-on-a-neutral-background-kQRtNeFxAcw',
    download: 'https://api.unsplash.com/photos/kQRtNeFxAcw/download?ixid=M3wxMDg2MDEwfDB8MXxzZWFyY2h8Mnx8dG9ydG9pc2VzaGVsbCUyMGdsYXNzZXN8ZW58MXx8fHwxNzkwOTQ1NDEyfDA',
  },
} satisfies Record<string, Photo>

export type PhotoKey = keyof typeof photos
